#pragma once
//定义支持的厂家
#define	PRODUCTOR_FOTRIC
#define	PRODUCTOR_BALSER

//定义厂家中的产品
#ifdef PRODUCTOR_FOTRIC
#define	CAMERA_SUPPORT_FOTRIC_IRVISION_GIGE_INFRARE
#endif // PRODUCTOR_FOTRIC

#ifdef PRODUCTOR_BALSER
#define	CAMERA_SUPPORT_BALSER_ACA_GIGE_GREY
#endif // PRODUCTOR_BALSER

