#pragma once
//定义支持的厂家
#define	PRODUCTOR_FOTRIC
#define	PRODUCTOR_BALSER
#define	PRODUCTOR_DO3THINK
#define	PRODUCTOR_DAHENG
//TODO:first,将支持的厂家定义到上面

//定义厂家中的产品
#ifdef PRODUCTOR_FOTRIC
#define	CAMERA_SUPPORT_FOTRIC_IRVISION_GIGE_INFRARE
#endif // PRODUCTOR_FOTRIC

#ifdef PRODUCTOR_BALSER
#define	CAMERA_SUPPORT_BALSER_ACA_GIGE_GREY
#endif // PRODUCTOR_BALSER

#ifdef PRODUCTOR_DO3THINK
#define	CAMERA_SUPPORT_DO3THINK_M2S_USB2_GREY
#endif // PRODUCTOR_DO3THINK

#ifdef PRODUCTOR_DAHENG
#define CAMERA_SUPPORT_DAHENG_MER_USB2_RGB
#endif // PRODUCTOR_DAHENG

//TODO:sencond，将厂家中相机定义在上面


